from setuptools import setup, find_packages

setup(
    name="c2-vlm",
    version="0.1.0",
    description="Contextual Contrastive Vision-Language Model",
    long_description=open("README.md").read(),
    long_description_content_type="text/markdown",
    author="Xiang Li",
    author_email="lixiang007666@gmail.com",
    url="https://github.com/lixiang007666/C2-VLM",
    packages=find_packages(where="src"),
    package_dir={"": "src"},
    python_requires=">=3.8",
    install_requires=[
        "torch>=1.12.0",
        "torchvision>=0.13.0",
        "transformers>=4.20.0",
        "numpy>=1.21.0",
        "pillow>=8.3.0",
        "datasets>=2.0.0",
        "opencv-python>=4.5.0",
        "albumentations>=1.2.0",
        "tensorboard>=2.9.0",
        "tqdm>=4.64.0",
        "scikit-learn>=1.1.0",
        "omegaconf>=2.2.0",
        "hydra-core>=1.2.0",
        "einops>=0.4.0",
        "timm>=0.6.0",
    ],
    extras_require={
        "dev": [
            "pytest>=7.0.0",
            "black>=22.0.0",
            "flake8>=4.0.0",
            "isort>=5.10.0",
        ],
        "distributed": [
            "deepspeed>=0.7.0",
        ],
        "wandb": [
            "wandb>=0.12.0",
        ],
    },
    classifiers=[
        "Development Status :: 3 - Alpha",
        "Intended Audience :: Developers",
        "Intended Audience :: Science/Research",
        "License :: OSI Approved :: MIT License",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
        "Topic :: Scientific/Engineering :: Artificial Intelligence",
        "Topic :: Software Development :: Libraries :: Python Modules",
    ],
    keywords="vision-language, multimodal, contrastive learning, deep learning, AI",
)